# Generated by Django 2.1 on 2019-02-18 09:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Comment_out', '0007_auto_20190218_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 18, 9, 23, 43, 92669, tzinfo=utc)),
        ),
    ]
