# Generated by Django 2.1 on 2019-02-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comment_out', '0011_auto_20190218_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.DateTimeField(),
        ),
    ]
