# Generated by Django 2.1 on 2019-02-18 10:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Comment_out', '0012_auto_20190218_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 18, 10, 16, 26, 340596, tzinfo=utc)),
        ),
    ]
